'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EStep
    Public Property Id As Integer
    Public Property Process As Integer
    Public Property type As Integer
    Public Property RunOrder As Integer
    Public Property PropertiesObj As String

    Public Overridable Property Process1 As EProcess
    Public Overridable Property StepType As EStepType

End Class
