'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class VBProjectContext
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=VBProjectContext")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property EProcesses() As DbSet(Of EProcess)
    Public Property ESteps() As DbSet(Of EStep)
    Public Property EStepTypes() As DbSet(Of EStepType)

End Class
